config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'stores#index'

  get 'search', to: 'pets#search'
  get 'store/inventory', to: 'stores#inventory'
  get 'sold', to: 'orders#sold'

  resources :pets
  resources :stores, path: 'store', only: [:index]
  resources :orders, path: 'store/order', only: %i[new create show destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :pet

  validates :user_email, email: true, presence: true
  validates :pet_id,
            numericality: { only_integer: true, greater_than: 0, message: 'ID must be a positive integer' },
            presence: { message: "ID can't be blank" }

  validate :pet_not_sold, on: :create

  before_create :generate_order_number, :set_order_date
  after_commit :toggle_sold
  after_commit :clear_cache, on: %i[update destroy]

  private

  def clear_cache
    Rails.cache.delete("order#{id}")
  end

  def generate_order_number
    loop do
      self.order_confirmation_number = SecureRandom.alphanumeric(10).upcase
      break unless Order.exists?(order_confirmation_number:)
    end
  end

  def set_order_date
    self.order_date = Time.zone.now
  end

  def toggle_sold
    pet.update(sold: !pet.sold)
  end

  def pet_not_sold
    errors.add(:pet, 'is already sold!') if pet&.sold
  end
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  has_one :order

  validates :age, numericality: { only_integer: true, greater_than: 0 }, presence: true
  validates :species, presence: true
  validates :name, presence: true
  validates :price, numericality: { less_than_or_equal_to: 999.99, greater_than: 0 }, presence: true

  after_commit :clear_cache, on: %i[create update destroy]

  private

  def clear_cache
    Rails.cache.delete("pet#{id}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/limit_helper.rb
# frozen_string_literal: true

extend Limiter::Mixin

module LimitHelper
  def limit(*methods)
    methods.each do |method|
      limit_method(method, rate: 5, interval: 1) { print 'Limit reached!' }
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  extend Limiter::Mixin
  extend LimitHelper

  include PetsHelper
  include OrdersHelper

  before_action :set_order, only: %i[show destroy]
  limit(:new, :show, :sold)

  def new
    @order = Order.new
    @order.pet = cached_pet_data
    session[:pet] = @order.pet.id
    pet_sold?
  end

  def create
    @order = Order.new(order_params)
    @order.pet = Pet.find_by_id(params[:order][:pet_id]) if params[:order][:pet_id]

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order }
        format.json { render json: @order }
      else
        format.html do
          render :new, status: :unprocessable_entity
        end
        format.json { render json: { errors: @order.errors.full_messages } }
      end
    end
  end

  def show
    respond_to do |format|
      if @order
        format.html
        format.json { render json: @order }
      else
        format.html { redirect_to stores_path, notice: 'Order not found' }
        format.json { render json: 'Record Not Found', status: :not_found }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @order
        @order.destroy
        format.html { redirect_to stores_path, notice: "Order for #{@order.pet.name} cancelled successfully!" }
        format.json { render json: "Order for #{@order.pet.name} successfully cancelled." }
      else
        format.json { render json: 'Record Not Found', status: :not_found }
      end
    end
  end

  def sold
    @pet = Pet.find(session[:pet])
  end

  private

  def order_params
    params.require(:order).permit(:user_email, :pet_id)
  end

  def set_order
    @order = cached_order_data
  end

  def pet_sold?
    if @order.pet.sold
      redirect_to :sold
    else
      render :new
    end
  end
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  extend Limiter::Mixin
  extend LimitHelper
  include PetsHelper

  before_action :authenticate_user!
  before_action :set_pet, only: %i[show edit update destroy]
  limit(:index, :new, :show, :edit, :search)

  def index
    @pet = Pet.order(:id)

    respond_to do |format|
      format.html
      format.json { render json: @pet }
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet }
        format.json { render json: { name: @pet.name, species: @pet.species, age: @pet.age, price: @pet.price } }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @pet.errors.full_messages } }
      end
    end
  end

  def show
    respond_to do |format|
      if @pet
        format.html { render :show }
        format.json { render json: @pet }
      else
        format.html { redirect_to pets_path, notice: 'Pet not found' }
        format.json { render json: 'Record Not Found', status: :not_found }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet }
        format.json { render json: { name: @pet.name, species: @pet.species, age: @pet.age, price: @pet.price } }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @pet.errors.full_messages } }
      end
    end
  end

  def search
    @search_query = params[:search]
    respond_to do |format|
      begin
        @pet = Pet.where('id = ?', Integer(@search_query))
      rescue ArgumentError
        @pet = Pet.where('name ILIKE ?', "%#{@search_query}%")
      end

      if @pet.empty?
        format.html { flash.now[:notice] = 'No pets found' }
        format.json { render json: { errors: 'No pets found' } }
      elsif @pet.count == 1
        format.html { redirect_to pet_path(@pet.first) }
        format.json { render json: @pet.first }
      end
      format.html
      format.json { render json: @pet }
    end
  end

  def destroy
    respond_to do |format|
      if @pet
        @pet.destroy
        format.html { redirect_to pets_path, notice: "#{@pet.name} deleted successfully." }
        format.json { render json: "#{@pet.name} deleted successfully." }
      else
        format.json { render json: 'Record Not Found', status: :not_found }
      end
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :price)
  end

  def set_pet
    @pet = cached_pet_data
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  extend Limiter::Mixin
  extend LimitHelper

  MAX_PETS_PER_PAGE = 24

  limit(:index, :inventory)

  def index
    @pet = Pet.where(sold: false).order(:id).paginate(page: params[:page], per_page: MAX_PETS_PER_PAGE)

    respond_to do |format|
      format.html
      format.json do
        render json: {
          page: params.fetch(:page, 1),
          number_of_pages: (Pet.count.to_f / MAX_PETS_PER_PAGE).ceil,
          pets: @pet
        }
      end
    end
  end

  def inventory
    @pet = Pet.all

    render json: {
      "sold": Pet.where(sold: true).count,
      "available": Pet.where(sold: false).count
    }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def cached_order_data
    Rails.cache.fetch("order#{params[:id]}", expires_in: 30.minutes) do
      Order.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/helpers/pets_helper.rb
# frozen_string_literal: true

module PetsHelper
  def pet_image_path(pet)
    pet_img = "#{pet.species.downcase}.jpg"
    pet_img = 'nil' unless File.exist?(Rails.root.join('app', 'assets', 'images', pet_img))
    pet_img
  end

  def cached_pet_data
    Rails.cache.fetch("pet#{params[:id]}", expires_in: 30.minutes) do
      Pet.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/_store_link.html.erb
<%= link_to 'Back to Store', stores_path, method: :get %>

app/views/orders/new.html.erb
<%= render 'store_link' %>

<h1>Order Pet</h1>

<% if @order.errors.any? %>
  <div>
    <h2><%= pluralize(@order.errors.count, 'error') %> prohibited this pet from being saved:</h2>
    <ul>
    <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <h2>Pet Info</h2>

  <table>
    <th>Name</th>
    <th>Species</th>
    <th>Age</th>
    <th>Price</th>
      <tr>
        <td><%= @order.pet.name %></td>
        <td><%= @order.pet.species %></td>
        <td><%= @order.pet.age %></td>
        <td>$<%= @order.pet.price %></td>
      </tr>
  </table><br />
  <div class="box">
    <div class="pet-image-container"><%= image_tag(pet_image_path(@order.pet), alt: 'Pet Image', class: 'pet-image') %></div>
  </div>
</div>

<%= form_with model: @order, url: orders_path, method: :post do |form| %>
  <%= form.label :user_email, 'Email ' %>
  <%= form.text_field :user_email, placeholder: 'user@example.com' %>

  <%= form.hidden_field :pet_id, value: @order.pet.id %>

  <%= form.submit 'Order' %>
<% end %>

app/views/orders/show.html.erb
<%= render 'store_link' %>

<h1>Order Details</h1>

<ul>
    <li>Order Confirmation Number: <%= @order.order_confirmation_number %></li>
    <li>Order Date: <%= @order.order_date %></li>
    <li>User Info: <%= @order.user_email %></li>
    <li>Pet: <%= @order.pet.name %></li>
    <li>Total: $<%= @order.pet.price %></li>
</ul>

<%= button_to "Cancel Order", order_path(@order.id), method: :delete, data: { turbo_confirm: "Cancel order for #{@order.pet.name}?" } %>

app/views/orders/sold.html.erb
<%= render 'store_link' %>

<h1><%= @pet.name %> has already found a home!</h1>

app/views/pets/_pet_table.html.erb
<% count = 1 %>
<table>
    <th>ID</th>
    <th>Name</th>
    <th>Species</th>
    <th>Age</th>
    <th>Price</th>
        <% @pet.each do |pet| %>
            <tr>
                <td><%= pet.id %></td>
                <td><%= pet.name %></td>
                <td><%= pet.species %></td>
                <td><%= pet.age %></td>
                <td>$<%= pet.price %></td>
                <td><%= link_to "Edit", edit_pet_path(pet.id) %></td>
                <td><%= button_to "Delete", pet_path(pet.id), method: :delete, data: { turbo_confirm: "Delete #{pet.name}?" } %></td>
            </tr>
            <% count += 1 %>
        <% end %>
</table>

app/views/pets/edit.html.erb
<%= link_to 'All Pets', pets_path %>

<h1>Edit Pet Details</h1>

<% if @pet.errors.any? %>
  <div>
    <h2><%= pluralize(@pet.errors.count, 'error') %> prohibited this pet from being saved:</h2>
    <ul>
    <% @pet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @pet, url: pet_path(@pet), method: :put) do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit 'Update Pet' %>
  </div>
<% end %>

app/views/pets/index.html.erb
<%= render 'orders/store_link' %>

<h1>List of Pets</h1>

<ul class="flex">
    <li><%= link_to "Add Pet", new_pet_path %></li>
    <li>
        <%= form_with url: '/search', method: :get do |form| %>
            <%= form.label :search, 'Search for pet' %>
            <%= form.text_field :search %>
            <%= form.submit 'Search' %>
        <% end %>
    </li>
</ul>

<div><%= render 'pet_table' %></div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<% if @pet.errors.any? %>
  <div>
    <h2><%= pluralize(@pet.errors.count, 'error') %> prohibited this pet from being saved:</h2>
    <ul>
    <% @pet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @pet, url: pets_path) do |form| %>
  
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :species %>
      <%= form.text_field :species %>
    </div>

    <div>
      <%= form.label :age %>
      <%= form.text_field :age %>
    </div>

    <div>
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div>
      <%= form.submit 'Add Pet' %>
    </div>
<% end %>

app/views/pets/search.html.erb
<%= link_to 'All Pets', pets_path %>

<h1>Search Results</h1>

<div><%= render 'pet_table' %></div>

app/views/pets/show.html.erb
<%= link_to 'All Pets', pets_path %>

<h1>Pet Information</h1>

<ul>
    <li>Name: <%= @pet.name %></li>
    <li>Species: <%= @pet.species %></li>
    <li>Age: <%= @pet.age %></li>
    <li>Price: <%= @pet.price %></li>
</ul>

<%= link_to 'Edit Pet', edit_pet_path %>

app/views/stores/index.html.erb
<% if user_signed_in? %>
 <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= button_to "Pet management", pets_path, method: :get %>
<% else %>
  <%= button_to "Sign in", new_user_session_path, method: :get %>
<% end %>

<h1>Petstore</h1>

<div class="grid-container">
  <% @pet.each do |pet| %>
    <% next if pet.sold == true %>
    <%= link_to new_order_path(id: pet.id) do %>
      <div class="box">
        <div class="pet-box">
          <div class="pet-image-container"><%= image_tag(pet_image_path(pet), alt: 'Pet Image', class: 'pet-image') %></div>
            <div class="pet-details">
              <div><%= pet.name %></div>
              <div>Age: <%= pet.age %></div>
            </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= will_paginate @pet, class: 'paginate' %>